services:
  # A Python web service
  - type: web
    name: ai-assistant-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_MODEL_NAME
        value: gemini-1.5-flash-latest
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      # ElevenLabs removed since it's not working